#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop aesdsocket daemon
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_ARGS=""
NAME=aesdsocket
PIDFILE=/var/run/$NAME.pid

case "$1" in
start)
    echo "Starting $NAME"
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
    ;;
stop)
    echo "Stopping $NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --signal TERM --retry 5
    rm -f $PIDFILE
    ;;
restart)
    "$0" stop
    "$0" start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
